apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-zerotohero-v1
  labels:
    app: app-zerotohero
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-zerotohero
      version: v1
  template:
    metadata:
      labels:
        app: app-zerotohero
        version: v1
    spec:
      containers:
        - name:  app-zerotohero
         ## image:
          ports:
            - containerPort: 9080
          securityContext:
            runAsUser: 1000
      imagePullSecrets:
        - name: regcred

