// +build !skippackr
// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr2 clean" command to clean up this,
// and any other packr generated files.
package packrd

import (
	"github.com/gobuffalo/packr/v2"
	"github.com/gobuffalo/packr/v2/file/resolver"
)

var _ = func() error {
	const gk = "a0eb2ce9fec3e8b32da87ae30caaee7d"
	g := packr.New(gk, "")
	hgr, err := resolver.NewHexGzip(map[string]string{
		"3a38e629eadb2bc2e4e9260adfab05cc": "1f8b08000000000000ff748fcf4a343110c4ef798a823d2fdf7eb725672f82878105ef6dd2cc049374ecf40aebd3cbfc5147d1ba0c9354d5af422d3db2f624d5835aebff5effbbe754a3c71db72cb7c2d55c61a34846de01950a2fd663fc32f4c661beec9c3998a8c701e5d65f320689b84c72cd1141aa51aae85418999e38770700852c4c0fcbbf5f0e30d7af8c3756319958c501c6a565325e5dfb51b3f2b786bf3a808fadb3b649acbbdc717be28fd8aa0352a1913deee70f1ad98464481d9d0da96214349551a9a43aee824dd4769015f4891f44cde37c3a9f36c74219ae395f3828db2ff394c7a01cdd7b000000ffffc2dc4e23c1010000",
	})
	if err != nil {
		panic(err)
	}
	g.DefaultResolver = hgr

	func() {
		b := packr.New("someBoxName", "./assets")
		b.SetResolver("deployment.yaml", packr.Pointer{ForwardBox: gk, ForwardPath: "3a38e629eadb2bc2e4e9260adfab05cc"})
	}()
	return nil
}()
